# must be unique in a given SonarQube instance
sonar.projectKey=algo_analysis

# --- optional properties ---

# defaults to project key
sonar.projectName=Algo
# source code
sonar.sources=.

# Go test coverage
sonar.go.coverage.reportPaths=coverage.out

# optional test report (if using JSON output tools)
# sonar.go.tests.reportPaths=report.json

# exclusions (VERY important for Go)
sonar.exclusions=**/vendor/**,**/*_test.go,**/main.go

# server
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8